baseURL = 'https://talperry.com/'
languageCode = 'en-us'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
title = 'Tal Perry'
theme = 'maverick'

[languages]
[languages.en]
languageName = 'English'
languageCode = 'en-US'
weight = 1

[languages.de]
languageName = 'Deutsch'
languageCode = 'de-DE'
weight = 2

[languages.he]
languageName = 'עברית'
languageCode = 'he-IL'
languageDirection = 'rtl'
weight = 3

[params]
description = 'Shouting into the void , now with AI.'
site_name = 'Tal Perry'
author_name = 'Tal Perry'
twitter_site = '@thetalperry'
twitter_creator = '@thetalperry'
default_og_image = '/og/default.png'

[menu]
[[menu.main]]
identifier = 'writing'
name = 'Writing'
url = '/posts/'
weight = 1
[[menu.main]]
identifier = 'projects'
name = 'Projects'
url = '/projects/'
weight = 2
[[menu.main]]
identifier = 'about'
name = 'About'
url = '/about/'
weight = 3
